DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
  id VARCHAR(250)  PRIMARY KEY,
  firstName VARCHAR(250) NOT NULL,
  lastName VARCHAR(250) NOT NULL,
  address VARCHAR(250) DEFAULT NULL,
  registeredOn DATE DEFAULT NULL
);